<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\group\Entity\Group;
use Drupal\group\Entity\GroupContent;

/**
 * Implements hook_help().
 */
function group_subdomain_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.group_subdomain':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Assign subdomains to groups') . '</p>';
      return $output;
  }
}
