<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function group_subdomain_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.group_subdomain':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Assign subdomains to groups') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\node\NodeForm.
 */
function group_subdomain_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  $form['group_subdomain_settings'] = array(
    '#type' => 'details',
    '#title' => t('Subdomain settings'),
    '#open' => !empty($form['group_subdomain']['widget'][0]['alias']['#value']),
    '#group' => 'advanced',
    '#access' => !empty($form['group_subdomain']['#access']) && $node->hasField('group_subdomain') && $node->get('group_subdomain')
        ->access('edit'),
    '#attributes' => array(
      'class' => array('group-subdomain-form'),
    ),
    '#weight' => 0,
  );
  $form['group_subdomain']['#group'] = 'group_subdomain_settings';
}

/**
 * Implements hook_entity_base_field_info().
 */
function group_subdomain_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {
    $fields['group_subdomain'] = BaseFieldDefinition::create('string')
      ->setDescription(t('The Group Subdomain alias for this site.'))
      ->setSettings(array(
        'default_value' => '',
        'max_length' => 64
      ))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'hidden',
        'weight' => -5,
      ])
      ->setDisplayOptions('form', [
        'type' => 'string',
        'weight' => 5,
        'disabled' => TRUE,
      ])
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', FALSE);

    return $fields;
  }
}

/**
 * Implements hook_token_info().
 */
function group_subdomain_token_info() {
  $info['tokens']['node']['group_subdomain'] = array(
    'name' => t('Group subdomain path'),
    'description' => t('The subdomain of the organic group the node is in.'),
  );

  return $info;
}

/**
 * Implements hook_tokens().
 */
function group_subdomain_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  if ($type == 'node') {
    // for each token passed in
    foreach ($tokens as $name => $original) {
      // if its name is group_subdomain
      switch ($name) {
        case 'group_subdomain':
          // if the node data is set in the options
          if (isset($data['node'])) {
            // need to get the organic group that this node belongs to
            // this is in the node__og_audience table
            // we get the first group audience defined
            $og_audience_value = $data['node']->og_audience->getValue();
            if (is_array($og_audience_value) && count($og_audience_value) > 0 && array_key_exists('target_id', $og_audience_value[0])) {
              // this is a member of a group
              $group_id = $og_audience_value[0]['target_id'];

              # find the node with this id, and replace the key with its subdomain
              if ($group_id != NULL) {
                $group_node = Node::load($group_id);
                if (!empty($group_node)) {
                  $replacements[$original] = $group_node->group_subdomain->getValue()[0]['value'];
                }
              }
            }
            else {
              // this could be a group/site itself. Check if it is
              if (!empty($subdomain = $data['node']->group_subdomain->getValue()[0]['value'])) {
                $replacements[$original] = $subdomain;
              }
            }
          }
          break;
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_link_alter().
 * @param $variables The variables to alter. (text, url, options)
 */
function group_subdomain_link_alter(&$variables) {
  // get the global base url out
  global $base_url;

  // find the route we are looking at rendering here
  $url = $variables['url'];
  $internal_path = $url->getInternalPath();

  // if it is a node route, get the organic group that this node belongs to
  $matches = array();
  if (preg_match('/^node\/(\d+)$/', $internal_path, $matches)) {
    $node_id = $matches[1];
    $node = Node::load($node_id);
    $og_audience = $node->og_audience;
    $og_audience_value = $og_audience->getValue();
    if (is_array($og_audience_value) && count($og_audience_value) > 0 && array_key_exists('target_id', $og_audience_value[0])) {
      // this is a member of a group
      $group_id = $og_audience_value[0]['target_id'];

      // now get THAT node and figure out its subdomain
      if ($group_id != NULL) {
        $group_node = Node::load($group_id);
        if (!empty($group_node)) {
          $subdomain = $group_node->group_subdomain->getValue()[0]['value'];

          // replace the subdomain in the base URL with this new one
          $split_base_url = explode('.', $base_url);
          $split_start = explode('/', $split_base_url[0]);
          $split_start[count($split_start) - 1] = $subdomain;
          $split_base_url[0] = implode('/', $split_start);
          $new_base_url = implode('.', $split_base_url);

          $variables['options']['base_url'] = $new_base_url;
          $url = $variables['url'];
          $url->setAbsolute();
          $variables['url'] = $url;
          $variables['options']['absolute'] = TRUE;
        }
      }
    }
    else {
      // this could be a group/site itself. Check if it is
      if (!empty($subdomain = $node->group_subdomain->getValue()[0]['value'])) {
        // replace the subdomain in the base URL with this new one
        $split_base_url = explode('.', $base_url);
        $split_start = explode('/', $split_base_url[0]);
        $split_start[count($split_start) - 1] = $subdomain;
        $split_base_url[0] = implode('/', $split_start);
        $new_base_url = implode('.', $split_base_url);

        $variables['options']['base_url'] = $new_base_url;
        $url = $variables['url'];
        $url->setAbsolute();
        $variables['url'] = $url;
        $variables['options']['absolute'] = TRUE;
      }
    }
  }
}
